name: build

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and publish UI bundle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up NodeJS 18
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Build project
      run: npm install

    - name: Create UI bundle
      run : gulp bundle
 
    - name: If pushed to main, delete 'latest' tag if any
      # if: github.event_name == 'push'
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}          
        script: |
          try {
            await github.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "tags/latest"
            })
            console.log("The 'latest' tag has been deleted")
          } catch (e) {
            console.log("The 'latest' tag doesn't exist yet: " + e)
          }

    - name: If pushed to main, set 'latest' tag on current build
      # if: github.event_name == 'push'
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ''
        custom_tag: latest

    - name: Publish UI bundle, as draft when not pushed to main
      uses: softprops/action-gh-release@v1
      with:
        name: UI bundle
        files: build/ui-bundle.zip
        # draft: ${{ github.event_name != 'push' }}
