name: build

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, JETUT-22_Fix_gulp_build_errors ]

jobs:
  build:
    name: Build and publish UI bundle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up NodeJS 18
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Build project
      run: npm install

    - name: Create UI bundle
      run : gulp bundle
 
    - name: Publish UI bundle
      # if: github.event_name == 'push'
      uses: ncipollo/release-action@v1
      with:
        name: UI bundle
        artifacts: build/ui-bundle.zip
        draft: true
