name: build

on: 
  push:
    tags: [ '*' ]
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and publish UI bundle
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up NodeJS 18
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Build project
      run: npm install

    - name: Create UI bundle
      run : gulp bundle
 
    - name: If pushed to main, set 'latest' tag on current build
      # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ''
        custom_tag: latest

    - name: If pushed to main, publish UI bundle
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        name: Latest UI bundle
        files: build/ui-bundle.zip
        tag_name: latest
