name: build

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and publish UI bundle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up NodeJS 18
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Build project
      run: npm install

    - name: Create UI bundle
      run : gulp bundle
 
    - name: Move 'latest' tag when main branch is pushed
      # if: github.event_name == 'push'
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}          
        script: |
          try {
            await github.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "tags/latest"
            })
            console.log("The 'latest' tag has been deleted')
          } catch (e) {
            console.log("The 'latest' tag doesn't exist yet: " + e)
          }
          await github.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/latest",
            sha: context.sha
          })
          console.log("The 'latest' tag has been set')

    - name: Publish UI bundle
      uses: softprops/action-gh-release@v1
      with:
        name: UI bundle
        files: build/ui-bundle.zip
        # draft: ${{ github.event_name != 'push' }}
